### ISSUE TITLE
about the content of the label files

### ISSUE THREAD

**Issue by xyxCalvin** [zcxu-eric/AVA-AVD#1]
Would you mind introducing the content of each column of the label files?

**Comment by zcxu-eric** [comment]
Hi, thanks for the interest. We have three file formats: `1.rttm 2.lab 3.csv`. 
1. For `rttm` file, please refer to https://github.com/nryant/dscore (section. V). 
2. `lab` file is the result of voice activity detection. Columns in the lab file are `start time, end time, speech label`
3. The `csv` file is similar to the original annotations from AVA challenge, please take a look at their descriptions https://research.google.com/ava/download.html#ava_active_speaker_download (section. AVA Active Speaker Download(v1.0)). In addition, we add one extra column which represents the speaker id.

Hope this clarifies.
