### ISSUE TITLE
Question about the baseline method

### ISSUE THREAD

**Issue by zaocan666** [zcxu-eric/AVA-AVD#3]
Hi, I have a question about the baseline method in the paper, but I cannot find your email, that's why I am asking here, sorry for the inappropriateness.
I wonder how the Speech+Face baseline in the 5.1.1 section is implemented. I assume the audio similarity and video similarity are obtained using pre-trained model, and the average of the similarity is calculated? Or it goes the other way. It would be helpful for me if you can provide the details.

**Comment by zcxu-eric** [comment]
Yes, two similarity scores are averaged. Sometimes the faces are invisible, we only use audio similarities for these cases.

**Comment by zaocan666** [comment]
Thank you a lot!
