### ISSUE TITLE
Label consistency between {uid}_c_01, {uid}_c_02, and {uid}_c_03

### ISSUE THREAD

**Issue by hbredin** [zcxu-eric/AVA-AVD#4]
Thanks for this great dataset.

If I understand correctly, 15 minutes of each video were annotated manually for speaker diarization.

However, those 15 minutes were split into three 5 minutes exceprt ([900 --> 1200], [1200 --> 1500], and [1500 --> 1800]).

My question relates to the consistency of the labels between those three excerpts.

Is `spk1` in `{uid}_c_01` guaranteed to be the same speaker as `spk1` in `{uid}_c_02` and `{uid}_c_03`?

**Comment by hbredin** [comment]
On a related note, in the "AVA-AVD: Audio-Visual Speaker Diarization in the Wild" paper, it is not clear to me whether the speaker diarization systems were evaluated on each 5min excerpts separately, or on the whole 15min at once?

**Comment by zcxu-eric** [comment]
Hello, 

The 5 min clips are annotated indepedently, which means the spk1 in c_01 could be different from spk1 in c_02.  During evaluation, the 5 min clips are evaluated separatedly. 

Thanks.

**Comment by hbredin** [comment]
Thanks for the answers!
