### ISSUE TITLE
Is this framework able to run on any video files?

### ISSUE THREAD

**Issue by dreamilization** [zcxu-eric/AVA-AVD#5]
Hi,

This is an interesting framework that we are looking to apply at one of our project. However, I'm currently stuck on preprocessing stage as it require to load the activespeaker csv for the video which I don't have. Would you please explain how this file is generated? Or point me a way so I can use your framework to inference on some of the video files that we have.

Thanks!

**Comment by zcxu-eric** [comment]
Hello,

Thanks for your interest. This repo contains only the final steps for AVD. To run on arbitrary videos, you may run all the preprocessing steps, including VAD, face detection&tracking, active speaker detection(ASD), and face alignment. We tried [this work](https://github.com/TaoRuijie/TalkNet-ASD) for ASD, though its performance may not be perfect.
